package com.LiteTravel.web.Model;

public class Company {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_company.company_id
     *
     * @mbg.generated Mon Dec 21 23:27:15 CST 2020
     */
    private Integer companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_company.company_name
     *
     * @mbg.generated Mon Dec 21 23:27:15 CST 2020
     */
    private String companyName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_company.company_id
     *
     * @return the value of travel_company.company_id
     *
     * @mbg.generated Mon Dec 21 23:27:15 CST 2020
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_company.company_id
     *
     * @param companyId the value for travel_company.company_id
     *
     * @mbg.generated Mon Dec 21 23:27:15 CST 2020
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_company.company_name
     *
     * @return the value of travel_company.company_name
     *
     * @mbg.generated Mon Dec 21 23:27:15 CST 2020
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_company.company_name
     *
     * @param companyName the value for travel_company.company_name
     *
     * @mbg.generated Mon Dec 21 23:27:15 CST 2020
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName == null ? null : companyName.trim();
    }
}