package com.LiteTravel.web.Model;

public class FlightReserve {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_flight_reserve.reserve_id
     *
     * @mbg.generated Sat Dec 19 17:33:10 CST 2020
     */
    private Integer reserveId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_flight_reserve.flight_id
     *
     * @mbg.generated Sat Dec 19 17:33:10 CST 2020
     */
    private Integer flightId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_flight_reserve.total
     *
     * @mbg.generated Sat Dec 19 17:33:10 CST 2020
     */
    private Float total;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_flight_reserve.seleted
     *
     * @mbg.generated Sat Dec 19 17:33:10 CST 2020
     */
    private Boolean seleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_flight_reserve.manager_id
     *
     * @mbg.generated Sat Dec 19 17:33:10 CST 2020
     */
    private Integer managerId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_flight_reserve.reserve_id
     *
     * @return the value of travel_flight_reserve.reserve_id
     *
     * @mbg.generated Sat Dec 19 17:33:10 CST 2020
     */
    public Integer getReserveId() {
        return reserveId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_flight_reserve.reserve_id
     *
     * @param reserveId the value for travel_flight_reserve.reserve_id
     *
     * @mbg.generated Sat Dec 19 17:33:10 CST 2020
     */
    public void setReserveId(Integer reserveId) {
        this.reserveId = reserveId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_flight_reserve.flight_id
     *
     * @return the value of travel_flight_reserve.flight_id
     *
     * @mbg.generated Sat Dec 19 17:33:10 CST 2020
     */
    public Integer getFlightId() {
        return flightId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_flight_reserve.flight_id
     *
     * @param flightId the value for travel_flight_reserve.flight_id
     *
     * @mbg.generated Sat Dec 19 17:33:10 CST 2020
     */
    public void setFlightId(Integer flightId) {
        this.flightId = flightId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_flight_reserve.total
     *
     * @return the value of travel_flight_reserve.total
     *
     * @mbg.generated Sat Dec 19 17:33:10 CST 2020
     */
    public Float getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_flight_reserve.total
     *
     * @param total the value for travel_flight_reserve.total
     *
     * @mbg.generated Sat Dec 19 17:33:10 CST 2020
     */
    public void setTotal(Float total) {
        this.total = total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_flight_reserve.seleted
     *
     * @return the value of travel_flight_reserve.seleted
     *
     * @mbg.generated Sat Dec 19 17:33:10 CST 2020
     */
    public Boolean getSeleted() {
        return seleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_flight_reserve.seleted
     *
     * @param seleted the value for travel_flight_reserve.seleted
     *
     * @mbg.generated Sat Dec 19 17:33:10 CST 2020
     */
    public void setSeleted(Boolean seleted) {
        this.seleted = seleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_flight_reserve.manager_id
     *
     * @return the value of travel_flight_reserve.manager_id
     *
     * @mbg.generated Sat Dec 19 17:33:10 CST 2020
     */
    public Integer getManagerId() {
        return managerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_flight_reserve.manager_id
     *
     * @param managerId the value for travel_flight_reserve.manager_id
     *
     * @mbg.generated Sat Dec 19 17:33:10 CST 2020
     */
    public void setManagerId(Integer managerId) {
        this.managerId = managerId;
    }
}