package com.LiteTravel.web.Model;

import java.util.Date;

public class HotelOrder {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_hotel_orders.order_id
     *
<<<<<<< Updated upstream
     * @mbg.generated Thu Dec 10 23:46:40 CST 2020
=======
     * @mbg.generated Sun Dec 20 22:43:15 CST 2020
>>>>>>> Stashed changes
     */
    private Integer orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_hotel_orders.hotel_id
     *
<<<<<<< Updated upstream
     * @mbg.generated Thu Dec 10 23:46:40 CST 2020
=======
     * @mbg.generated Sun Dec 20 22:43:15 CST 2020
>>>>>>> Stashed changes
     */
    private Integer hotelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_hotel_orders.user_id
     *
<<<<<<< Updated upstream
     * @mbg.generated Thu Dec 10 23:46:40 CST 2020
=======
     * @mbg.generated Sun Dec 20 22:43:15 CST 2020
>>>>>>> Stashed changes
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_hotel_orders.user_phone
     *
<<<<<<< Updated upstream
     * @mbg.generated Thu Dec 10 23:46:40 CST 2020
=======
     * @mbg.generated Sun Dec 20 22:43:15 CST 2020
>>>>>>> Stashed changes
     */
    private String userPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_hotel_orders.user_name
     *
<<<<<<< Updated upstream
     * @mbg.generated Thu Dec 10 23:46:40 CST 2020
=======
     * @mbg.generated Sun Dec 20 22:43:15 CST 2020
>>>>>>> Stashed changes
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_hotel_orders.when_arrived
     *
<<<<<<< Updated upstream
     * @mbg.generated Thu Dec 10 23:46:40 CST 2020
=======
     * @mbg.generated Sun Dec 20 22:43:15 CST 2020
>>>>>>> Stashed changes
     */
    private String whenArrived;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_hotel_orders.days
     *
<<<<<<< Updated upstream
     * @mbg.generated Thu Dec 10 23:46:40 CST 2020
=======
     * @mbg.generated Sun Dec 20 22:43:15 CST 2020
>>>>>>> Stashed changes
     */
    private Integer days;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_hotel_orders.status
     *
<<<<<<< Updated upstream
     * @mbg.generated Thu Dec 10 23:46:40 CST 2020
=======
     * @mbg.generated Sun Dec 20 22:43:15 CST 2020
>>>>>>> Stashed changes
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_hotel_orders.check_in
     *
<<<<<<< Updated upstream
     * @mbg.generated Thu Dec 10 23:46:40 CST 2020
=======
     * @mbg.generated Sun Dec 20 22:43:15 CST 2020
>>>>>>> Stashed changes
     */
    private Date checkIn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_hotel_orders.check_out
     *
<<<<<<< Updated upstream
     * @mbg.generated Thu Dec 10 23:46:40 CST 2020
=======
     * @mbg.generated Sun Dec 20 22:43:15 CST 2020
>>>>>>> Stashed changes
     */
    private Date checkOut;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_hotel_orders.create_date
     *
<<<<<<< Updated upstream
     * @mbg.generated Thu Dec 10 23:46:40 CST 2020
=======
     * @mbg.generated Sun Dec 20 22:43:15 CST 2020
>>>>>>> Stashed changes
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_hotel_orders.pay_date
     *
<<<<<<< Updated upstream
     * @mbg.generated Thu Dec 10 23:46:40 CST 2020
=======
     * @mbg.generated Sun Dec 20 22:43:15 CST 2020
>>>>>>> Stashed changes
     */
    private Date payDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_hotel_orders.confirm_check_in
     *
<<<<<<< Updated upstream
     * @mbg.generated Thu Dec 10 23:46:40 CST 2020
=======
     * @mbg.generated Sun Dec 20 22:43:15 CST 2020
>>>>>>> Stashed changes
     */
    private Date confirmCheckIn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_hotel_orders.confirm_check_out
     *
<<<<<<< Updated upstream
     * @mbg.generated Thu Dec 10 23:46:40 CST 2020
=======
     * @mbg.generated Sun Dec 20 22:43:15 CST 2020
>>>>>>> Stashed changes
     */
    private Date confirmCheckOut;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_hotel_orders.total
     *
<<<<<<< Updated upstream
     * @mbg.generated Thu Dec 10 23:46:40 CST 2020
=======
     * @mbg.generated Sun Dec 20 22:43:15 CST 2020
>>>>>>> Stashed changes
     */
    private Float total;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_hotel_orders.note
     *
<<<<<<< Updated upstream
     * @mbg.generated Thu Dec 10 23:46:40 CST 2020
=======
     * @mbg.generated Sun Dec 20 22:43:15 CST 2020
>>>>>>> Stashed changes
     */
    private String note;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_hotel_orders.order_id
     *
     * @return the value of travel_hotel_orders.order_id
     *
<<<<<<< Updated upstream
     * @mbg.generated Thu Dec 10 23:46:40 CST 2020
=======
     * @mbg.generated Sun Dec 20 22:43:15 CST 2020
>>>>>>> Stashed changes
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_hotel_orders.order_id
     *
     * @param orderId the value for travel_hotel_orders.order_id
     *
<<<<<<< Updated upstream
     * @mbg.generated Thu Dec 10 23:46:40 CST 2020
=======
     * @mbg.generated Sun Dec 20 22:43:15 CST 2020
>>>>>>> Stashed changes
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_hotel_orders.hotel_id
     *
     * @return the value of travel_hotel_orders.hotel_id
     *
<<<<<<< Updated upstream
     * @mbg.generated Thu Dec 10 23:46:40 CST 2020
=======
     * @mbg.generated Sun Dec 20 22:43:15 CST 2020
>>>>>>> Stashed changes
     */
    public Integer getHotelId() {
        return hotelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_hotel_orders.hotel_id
     *
     * @param hotelId the value for travel_hotel_orders.hotel_id
     *
<<<<<<< Updated upstream
     * @mbg.generated Thu Dec 10 23:46:40 CST 2020
=======
     * @mbg.generated Sun Dec 20 22:43:15 CST 2020
>>>>>>> Stashed changes
     */
    public void setHotelId(Integer hotelId) {
        this.hotelId = hotelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_hotel_orders.user_id
     *
     * @return the value of travel_hotel_orders.user_id
     *
<<<<<<< Updated upstream
     * @mbg.generated Thu Dec 10 23:46:40 CST 2020
=======
     * @mbg.generated Sun Dec 20 22:43:15 CST 2020
>>>>>>> Stashed changes
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_hotel_orders.user_id
     *
     * @param userId the value for travel_hotel_orders.user_id
     *
<<<<<<< Updated upstream
     * @mbg.generated Thu Dec 10 23:46:40 CST 2020
=======
     * @mbg.generated Sun Dec 20 22:43:15 CST 2020
>>>>>>> Stashed changes
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_hotel_orders.user_phone
     *
     * @return the value of travel_hotel_orders.user_phone
     *
<<<<<<< Updated upstream
     * @mbg.generated Thu Dec 10 23:46:40 CST 2020
=======
     * @mbg.generated Sun Dec 20 22:43:15 CST 2020
>>>>>>> Stashed changes
     */
    public String getUserPhone() {
        return userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_hotel_orders.user_phone
     *
     * @param userPhone the value for travel_hotel_orders.user_phone
     *
<<<<<<< Updated upstream
     * @mbg.generated Thu Dec 10 23:46:40 CST 2020
=======
     * @mbg.generated Sun Dec 20 22:43:15 CST 2020
>>>>>>> Stashed changes
     */
    public void setUserPhone(String userPhone) {
        this.userPhone = userPhone == null ? null : userPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_hotel_orders.user_name
     *
     * @return the value of travel_hotel_orders.user_name
     *
<<<<<<< Updated upstream
     * @mbg.generated Thu Dec 10 23:46:40 CST 2020
=======
     * @mbg.generated Sun Dec 20 22:43:15 CST 2020
>>>>>>> Stashed changes
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_hotel_orders.user_name
     *
     * @param userName the value for travel_hotel_orders.user_name
     *
<<<<<<< Updated upstream
     * @mbg.generated Thu Dec 10 23:46:40 CST 2020
=======
     * @mbg.generated Sun Dec 20 22:43:15 CST 2020
>>>>>>> Stashed changes
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_hotel_orders.when_arrived
     *
     * @return the value of travel_hotel_orders.when_arrived
     *
<<<<<<< Updated upstream
     * @mbg.generated Thu Dec 10 23:46:40 CST 2020
=======
     * @mbg.generated Sun Dec 20 22:43:15 CST 2020
>>>>>>> Stashed changes
     */
    public String getWhenArrived() {
        return whenArrived;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_hotel_orders.when_arrived
     *
     * @param whenArrived the value for travel_hotel_orders.when_arrived
     *
<<<<<<< Updated upstream
     * @mbg.generated Thu Dec 10 23:46:40 CST 2020
=======
     * @mbg.generated Sun Dec 20 22:43:15 CST 2020
>>>>>>> Stashed changes
     */
    public void setWhenArrived(String whenArrived) {
        this.whenArrived = whenArrived == null ? null : whenArrived.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_hotel_orders.days
     *
     * @return the value of travel_hotel_orders.days
     *
<<<<<<< Updated upstream
     * @mbg.generated Thu Dec 10 23:46:40 CST 2020
=======
     * @mbg.generated Sun Dec 20 22:43:15 CST 2020
>>>>>>> Stashed changes
     */
    public Integer getDays() {
        return days;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_hotel_orders.days
     *
     * @param days the value for travel_hotel_orders.days
     *
<<<<<<< Updated upstream
     * @mbg.generated Thu Dec 10 23:46:40 CST 2020
=======
     * @mbg.generated Sun Dec 20 22:43:15 CST 2020
>>>>>>> Stashed changes
     */
    public void setDays(Integer days) {
        this.days = days;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_hotel_orders.status
     *
     * @return the value of travel_hotel_orders.status
     *
<<<<<<< Updated upstream
     * @mbg.generated Thu Dec 10 23:46:40 CST 2020
=======
     * @mbg.generated Sun Dec 20 22:43:15 CST 2020
>>>>>>> Stashed changes
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_hotel_orders.status
     *
     * @param status the value for travel_hotel_orders.status
     *
<<<<<<< Updated upstream
     * @mbg.generated Thu Dec 10 23:46:40 CST 2020
=======
     * @mbg.generated Sun Dec 20 22:43:15 CST 2020
>>>>>>> Stashed changes
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_hotel_orders.check_in
     *
     * @return the value of travel_hotel_orders.check_in
     *
<<<<<<< Updated upstream
     * @mbg.generated Thu Dec 10 23:46:40 CST 2020
=======
     * @mbg.generated Sun Dec 20 22:43:15 CST 2020
>>>>>>> Stashed changes
     */
    public Date getCheckIn() {
        return checkIn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_hotel_orders.check_in
     *
     * @param checkIn the value for travel_hotel_orders.check_in
     *
<<<<<<< Updated upstream
     * @mbg.generated Thu Dec 10 23:46:40 CST 2020
=======
     * @mbg.generated Sun Dec 20 22:43:15 CST 2020
>>>>>>> Stashed changes
     */
    public void setCheckIn(Date checkIn) {
        this.checkIn = checkIn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_hotel_orders.check_out
     *
     * @return the value of travel_hotel_orders.check_out
     *
<<<<<<< Updated upstream
     * @mbg.generated Thu Dec 10 23:46:40 CST 2020
=======
     * @mbg.generated Sun Dec 20 22:43:15 CST 2020
>>>>>>> Stashed changes
     */
    public Date getCheckOut() {
        return checkOut;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_hotel_orders.check_out
     *
     * @param checkOut the value for travel_hotel_orders.check_out
     *
<<<<<<< Updated upstream
     * @mbg.generated Thu Dec 10 23:46:40 CST 2020
=======
     * @mbg.generated Sun Dec 20 22:43:15 CST 2020
>>>>>>> Stashed changes
     */
    public void setCheckOut(Date checkOut) {
        this.checkOut = checkOut;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_hotel_orders.create_date
     *
     * @return the value of travel_hotel_orders.create_date
     *
<<<<<<< Updated upstream
     * @mbg.generated Thu Dec 10 23:46:40 CST 2020
=======
     * @mbg.generated Sun Dec 20 22:43:15 CST 2020
>>>>>>> Stashed changes
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_hotel_orders.create_date
     *
     * @param createDate the value for travel_hotel_orders.create_date
     *
<<<<<<< Updated upstream
     * @mbg.generated Thu Dec 10 23:46:40 CST 2020
=======
     * @mbg.generated Sun Dec 20 22:43:15 CST 2020
>>>>>>> Stashed changes
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_hotel_orders.pay_date
     *
     * @return the value of travel_hotel_orders.pay_date
     *
<<<<<<< Updated upstream
     * @mbg.generated Thu Dec 10 23:46:40 CST 2020
=======
     * @mbg.generated Sun Dec 20 22:43:15 CST 2020
>>>>>>> Stashed changes
     */
    public Date getPayDate() {
        return payDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_hotel_orders.pay_date
     *
     * @param payDate the value for travel_hotel_orders.pay_date
     *
<<<<<<< Updated upstream
     * @mbg.generated Thu Dec 10 23:46:40 CST 2020
=======
     * @mbg.generated Sun Dec 20 22:43:15 CST 2020
>>>>>>> Stashed changes
     */
    public void setPayDate(Date payDate) {
        this.payDate = payDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_hotel_orders.confirm_check_in
     *
     * @return the value of travel_hotel_orders.confirm_check_in
     *
<<<<<<< Updated upstream
     * @mbg.generated Thu Dec 10 23:46:40 CST 2020
=======
     * @mbg.generated Sun Dec 20 22:43:15 CST 2020
>>>>>>> Stashed changes
     */
    public Date getConfirmCheckIn() {
        return confirmCheckIn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_hotel_orders.confirm_check_in
     *
     * @param confirmCheckIn the value for travel_hotel_orders.confirm_check_in
     *
<<<<<<< Updated upstream
     * @mbg.generated Thu Dec 10 23:46:40 CST 2020
=======
     * @mbg.generated Sun Dec 20 22:43:15 CST 2020
>>>>>>> Stashed changes
     */
    public void setConfirmCheckIn(Date confirmCheckIn) {
        this.confirmCheckIn = confirmCheckIn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_hotel_orders.confirm_check_out
     *
     * @return the value of travel_hotel_orders.confirm_check_out
     *
<<<<<<< Updated upstream
     * @mbg.generated Thu Dec 10 23:46:40 CST 2020
=======
     * @mbg.generated Sun Dec 20 22:43:15 CST 2020
>>>>>>> Stashed changes
     */
    public Date getConfirmCheckOut() {
        return confirmCheckOut;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_hotel_orders.confirm_check_out
     *
     * @param confirmCheckOut the value for travel_hotel_orders.confirm_check_out
     *
<<<<<<< Updated upstream
     * @mbg.generated Thu Dec 10 23:46:40 CST 2020
=======
     * @mbg.generated Sun Dec 20 22:43:15 CST 2020
>>>>>>> Stashed changes
     */
    public void setConfirmCheckOut(Date confirmCheckOut) {
        this.confirmCheckOut = confirmCheckOut;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_hotel_orders.total
     *
     * @return the value of travel_hotel_orders.total
     *
<<<<<<< Updated upstream
     * @mbg.generated Thu Dec 10 23:46:40 CST 2020
=======
     * @mbg.generated Sun Dec 20 22:43:15 CST 2020
>>>>>>> Stashed changes
     */
    public Float getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_hotel_orders.total
     *
     * @param total the value for travel_hotel_orders.total
     *
<<<<<<< Updated upstream
     * @mbg.generated Thu Dec 10 23:46:40 CST 2020
=======
     * @mbg.generated Sun Dec 20 22:43:15 CST 2020
>>>>>>> Stashed changes
     */
    public void setTotal(Float total) {
        this.total = total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_hotel_orders.note
     *
     * @return the value of travel_hotel_orders.note
     *
<<<<<<< Updated upstream
     * @mbg.generated Thu Dec 10 23:46:40 CST 2020
=======
     * @mbg.generated Sun Dec 20 22:43:15 CST 2020
>>>>>>> Stashed changes
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_hotel_orders.note
     *
     * @param note the value for travel_hotel_orders.note
     *
<<<<<<< Updated upstream
     * @mbg.generated Thu Dec 10 23:46:40 CST 2020
=======
     * @mbg.generated Sun Dec 20 22:43:15 CST 2020
>>>>>>> Stashed changes
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }
}