package com.LiteTravel.web.Model;

public class Region {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_region.id
     *
     * @mbg.generated Sun Dec 20 16:52:53 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_region.name
     *
     * @mbg.generated Sun Dec 20 16:52:53 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_region.pid
     *
     * @mbg.generated Sun Dec 20 16:52:53 CST 2020
     */
    private Integer pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_region.sname
     *
     * @mbg.generated Sun Dec 20 16:52:53 CST 2020
     */
    private String sname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_region.level
     *
     * @mbg.generated Sun Dec 20 16:52:53 CST 2020
     */
    private Integer level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_region.citycode
     *
     * @mbg.generated Sun Dec 20 16:52:53 CST 2020
     */
    private String citycode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_region.yzcode
     *
     * @mbg.generated Sun Dec 20 16:52:53 CST 2020
     */
    private String yzcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_region.mername
     *
     * @mbg.generated Sun Dec 20 16:52:53 CST 2020
     */
    private String mername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_region.Lng
     *
     * @mbg.generated Sun Dec 20 16:52:53 CST 2020
     */
    private Float lng;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_region.Lat
     *
     * @mbg.generated Sun Dec 20 16:52:53 CST 2020
     */
    private Float lat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_region.pinyin
     *
     * @mbg.generated Sun Dec 20 16:52:53 CST 2020
     */
    private String pinyin;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_region.id
     *
     * @return the value of global_region.id
     *
     * @mbg.generated Sun Dec 20 16:52:53 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_region.id
     *
     * @param id the value for global_region.id
     *
     * @mbg.generated Sun Dec 20 16:52:53 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_region.name
     *
     * @return the value of global_region.name
     *
     * @mbg.generated Sun Dec 20 16:52:53 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_region.name
     *
     * @param name the value for global_region.name
     *
     * @mbg.generated Sun Dec 20 16:52:53 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_region.pid
     *
     * @return the value of global_region.pid
     *
     * @mbg.generated Sun Dec 20 16:52:53 CST 2020
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_region.pid
     *
     * @param pid the value for global_region.pid
     *
     * @mbg.generated Sun Dec 20 16:52:53 CST 2020
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_region.sname
     *
     * @return the value of global_region.sname
     *
     * @mbg.generated Sun Dec 20 16:52:53 CST 2020
     */
    public String getSname() {
        return sname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_region.sname
     *
     * @param sname the value for global_region.sname
     *
     * @mbg.generated Sun Dec 20 16:52:53 CST 2020
     */
    public void setSname(String sname) {
        this.sname = sname == null ? null : sname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_region.level
     *
     * @return the value of global_region.level
     *
     * @mbg.generated Sun Dec 20 16:52:53 CST 2020
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_region.level
     *
     * @param level the value for global_region.level
     *
     * @mbg.generated Sun Dec 20 16:52:53 CST 2020
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_region.citycode
     *
     * @return the value of global_region.citycode
     *
     * @mbg.generated Sun Dec 20 16:52:53 CST 2020
     */
    public String getCitycode() {
        return citycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_region.citycode
     *
     * @param citycode the value for global_region.citycode
     *
     * @mbg.generated Sun Dec 20 16:52:53 CST 2020
     */
    public void setCitycode(String citycode) {
        this.citycode = citycode == null ? null : citycode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_region.yzcode
     *
     * @return the value of global_region.yzcode
     *
     * @mbg.generated Sun Dec 20 16:52:53 CST 2020
     */
    public String getYzcode() {
        return yzcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_region.yzcode
     *
     * @param yzcode the value for global_region.yzcode
     *
     * @mbg.generated Sun Dec 20 16:52:53 CST 2020
     */
    public void setYzcode(String yzcode) {
        this.yzcode = yzcode == null ? null : yzcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_region.mername
     *
     * @return the value of global_region.mername
     *
     * @mbg.generated Sun Dec 20 16:52:53 CST 2020
     */
    public String getMername() {
        return mername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_region.mername
     *
     * @param mername the value for global_region.mername
     *
     * @mbg.generated Sun Dec 20 16:52:53 CST 2020
     */
    public void setMername(String mername) {
        this.mername = mername == null ? null : mername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_region.Lng
     *
     * @return the value of global_region.Lng
     *
     * @mbg.generated Sun Dec 20 16:52:53 CST 2020
     */
    public Float getLng() {
        return lng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_region.Lng
     *
     * @param lng the value for global_region.Lng
     *
     * @mbg.generated Sun Dec 20 16:52:53 CST 2020
     */
    public void setLng(Float lng) {
        this.lng = lng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_region.Lat
     *
     * @return the value of global_region.Lat
     *
     * @mbg.generated Sun Dec 20 16:52:53 CST 2020
     */
    public Float getLat() {
        return lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_region.Lat
     *
     * @param lat the value for global_region.Lat
     *
     * @mbg.generated Sun Dec 20 16:52:53 CST 2020
     */
    public void setLat(Float lat) {
        this.lat = lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_region.pinyin
     *
     * @return the value of global_region.pinyin
     *
     * @mbg.generated Sun Dec 20 16:52:53 CST 2020
     */
    public String getPinyin() {
        return pinyin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_region.pinyin
     *
     * @param pinyin the value for global_region.pinyin
     *
     * @mbg.generated Sun Dec 20 16:52:53 CST 2020
     */
    public void setPinyin(String pinyin) {
        this.pinyin = pinyin == null ? null : pinyin.trim();
    }
}