package com.LiteTravel.web.Model;

public class userAuthority {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_user_authority.user_id
     *
     * @mbg.generated Mon Dec 21 23:27:15 CST 2020
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_user_authority.authority_level
     *
     * @mbg.generated Mon Dec 21 23:27:15 CST 2020
     */
    private Boolean authorityLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_user_authority.user_authority
     *
     * @mbg.generated Mon Dec 21 23:27:15 CST 2020
     */
    private Boolean userAuthority;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_user_authority.hotel_authority
     *
     * @mbg.generated Mon Dec 21 23:27:15 CST 2020
     */
    private Boolean hotelAuthority;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_user_authority.flight_authority
     *
     * @mbg.generated Mon Dec 21 23:27:15 CST 2020
     */
    private Boolean flightAuthority;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_user_authority.guide_authority
     *
     * @mbg.generated Mon Dec 21 23:27:15 CST 2020
     */
    private Boolean guideAuthority;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_user_authority.user_id
     *
     * @return the value of travel_user_authority.user_id
     *
     * @mbg.generated Mon Dec 21 23:27:15 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_user_authority.user_id
     *
     * @param userId the value for travel_user_authority.user_id
     *
     * @mbg.generated Mon Dec 21 23:27:15 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_user_authority.authority_level
     *
     * @return the value of travel_user_authority.authority_level
     *
     * @mbg.generated Mon Dec 21 23:27:15 CST 2020
     */
    public Boolean getAuthorityLevel() {
        return authorityLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_user_authority.authority_level
     *
     * @param authorityLevel the value for travel_user_authority.authority_level
     *
     * @mbg.generated Mon Dec 21 23:27:15 CST 2020
     */
    public void setAuthorityLevel(Boolean authorityLevel) {
        this.authorityLevel = authorityLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_user_authority.user_authority
     *
     * @return the value of travel_user_authority.user_authority
     *
     * @mbg.generated Mon Dec 21 23:27:15 CST 2020
     */
    public Boolean getUserAuthority() {
        return userAuthority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_user_authority.user_authority
     *
     * @param userAuthority the value for travel_user_authority.user_authority
     *
     * @mbg.generated Mon Dec 21 23:27:15 CST 2020
     */
    public void setUserAuthority(Boolean userAuthority) {
        this.userAuthority = userAuthority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_user_authority.hotel_authority
     *
     * @return the value of travel_user_authority.hotel_authority
     *
     * @mbg.generated Mon Dec 21 23:27:15 CST 2020
     */
    public Boolean getHotelAuthority() {
        return hotelAuthority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_user_authority.hotel_authority
     *
     * @param hotelAuthority the value for travel_user_authority.hotel_authority
     *
     * @mbg.generated Mon Dec 21 23:27:15 CST 2020
     */
    public void setHotelAuthority(Boolean hotelAuthority) {
        this.hotelAuthority = hotelAuthority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_user_authority.flight_authority
     *
     * @return the value of travel_user_authority.flight_authority
     *
     * @mbg.generated Mon Dec 21 23:27:15 CST 2020
     */
    public Boolean getFlightAuthority() {
        return flightAuthority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_user_authority.flight_authority
     *
     * @param flightAuthority the value for travel_user_authority.flight_authority
     *
     * @mbg.generated Mon Dec 21 23:27:15 CST 2020
     */
    public void setFlightAuthority(Boolean flightAuthority) {
        this.flightAuthority = flightAuthority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_user_authority.guide_authority
     *
     * @return the value of travel_user_authority.guide_authority
     *
     * @mbg.generated Mon Dec 21 23:27:15 CST 2020
     */
    public Boolean getGuideAuthority() {
        return guideAuthority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_user_authority.guide_authority
     *
     * @param guideAuthority the value for travel_user_authority.guide_authority
     *
     * @mbg.generated Mon Dec 21 23:27:15 CST 2020
     */
    public void setGuideAuthority(Boolean guideAuthority) {
        this.guideAuthority = guideAuthority;
    }
}