spring.datasource:
  url: jdbc:mysql://localhost:3306/travelsystem?useUnicode=true&characterEncoding=utf8&useSSL=false
  username: root
  password: root3306
  driver-class-name: com.mysql.cj.jdbc.Driver
  database: mysql8015