server:
  port: 8080
spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  application:
    name: lite-travel
  datasource:
    url: jdbc:mysql://106.52.223.207/travel_database?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    password: "#Huang888666"
    schema-username: root
    schema-password: "#Huang888666"
    data-username: root
    data-password: "#Huang888666"
    driver-class-name: com.mysql.cj.jdbc.Driver
    sql-script-encoding: utf-8
    initialization-mode: ALWAYS
# Other Configs
logging.level.org.springframework.security: DEBUG
#mybatis 基本配置
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
logging:
  level:
    com.LiteTravel.web.mapper: debug