#spring:
#  profiles: development
#  datasource:
#    url: jdbc:mysql://localhost:3306/SQLconnect?useUnicode=true&characterEncoding=utf8&useSSL=false
#    username: root
#    password: root3306
#    schema-username: root
#    schema-password: root3306
#    data-username: root
#    data-password: root3306
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    schema:
#      - classpath:department.sql
#    # Hikari will use the above plus the following to setup connection pooling
#    # 用Hikari替代Druid，更快更便捷
#    type: com.zaxxer.hikari.HikariDataSource
#    hikari:
#      minimum-idle: 5
#      maximum-pool-size: 15
#      auto-commit: true
#      idle-timeout: 30000
#      pool-name: DatebookHikariCP
#      max-lifetime: 1800000
#      connection-timeout: 30000
#      connection-test-query: SELECT 1
#    # Other Configs
#    platform: mysql
#    initialization-mode: always
#    continue-on-error: true
#logging:
#  level:
#    org.springframework.security: DEBUG

#spring:
#  datasource:
#    username: root
#    password: root3306
#    driver-class-name: com.mysql.cj.jdbc.Driver  # mysql8.0以前使用com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/SQLconnect?useUnicode=true&characterEncoding=utf8&useSSL=false
#    druid:
#      initial-size: 5  # 初始化大小
#      min-idle: 5  # 最小
#      max-active: 100  # 最大s
#      max-wait: 60000  # 连接超时时间
#      time-between-eviction-runs-millis: 60000  # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
#      min-evictable-idle-time-millis: 300000  # 指定一个空闲连接最少空闲多久后可被清除，单位是毫秒
#      validationQuery: select 'x'
#      test-while-idle: true  # 当连接空闲时，是否执行连接测试
#      test-on-borrow: false  # 当从连接池借用连接时，是否测试该连接
#      test-on-return: false  # 在连接归还到连接池时是否测试该连接
#      filters: config,wall,stat  # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
#      poolPreparedStatements: true
#      maxPoolPreparedStatementPerConnectionSize: 20
#      maxOpenPreparedStatements: 20
#      connectionProperties: druid.stat.slowSqlMillis=200;druid.stat.logSlowSql=true;config.decrypt=true
#      web-stat-filter:
#        enabled: true
#        url-pattern: /*
#        exclusions: /druid/*,*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico
#        session-stat-enable: true
#        session-stat-max-count: 10
#      stat-view-servlet:
#        enabled: true
#        url-pattern: /druid/*
#        reset-enable: true
#        login-username: admin
#        login-password: admin