# SpringCloud Service配置
server:
  port: 8001

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
# DataBase配置
spring:
  application:
    name: frontend
  datasource:
    url: jdbc:mysql://106.52.223.207:3306/travel_database?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&allowMultiQueries=true
    username: root
    password: "#Huang888666"
#    schema-username: root
#    schema-password: /#Huang888666
#    data-username: root
#    data-password: /#Huang888666
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    schema:
    #      - classpath:department.sql
    #      - classpath:employee.sql
    # 配置Druid
    type: com.alibaba.druid.pool.DruidDataSource
    # 连接池的设置
    # 初始化时建立物理连接的个数
    druid:
      initial-size: 5
      #最小连接池数量
      min-idle: 5
      #最大连接池数量 maxIdle已经不再使用
      max-active: 20
      #获取连接时最大等待时间，单位毫秒
      max-wait: 60000
      #申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      test-while-idle: true
      #既作为检测的间隔时间又作为testWhileIdel执行的依据
      time-between-eviction-runs-millis: 60000
      #销毁线程时检测当前连接的最后活动时间和当前时间差大于该值时，关闭当前连接
      min-evictable-idle-time-millis: 30000
      #用来检测连接是否有效的sql 必须是一个查询语句
      #mysql中为 select 'x' #oracle中为 select 1 from dual
      validation-query: select 'x'
      #申请连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
      test-on-borrow: false
      #归还连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
      test-on-return: false
      #当数据库抛出不可恢复的异常时,抛弃该连接
      #是否缓存preparedStatement,mysql5.5+建议开启
      pool-prepared-statements: true
      #当值大于0时poolPreparedStatements会自动修改为true
      max-pool-prepared-statement-per-connection-size: 20
      #配置扩展插件
      filters: stat,wall
      #通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
      #合并多个DruidDataSource的监控数据
      use-global-data-source-stat: true
      #设置访问druid监控页的账号和密码,默认没有
      stat-view-servlet.login-username: admin
      stat-view-servlet.login-password: admin
    sql-script-encoding: utf-8
    initialization-mode: ALWAYS
  #jpa设置
  jpa.database: mysql
  jpa.show-sql: true
  jpa.hibernate.ddl-auto: update
# Other Configs
logging.level.org.springframework.security: DEBUG
#mybatis 基本配置
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
logging:
  level:
    com.LiteTravel.web.Mapper: debug


# cache配置