package com.LiteTravel.web.mapper;

import com.LiteTravel.web.Model.Bed;
import com.LiteTravel.web.Model.BedExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BedMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_bed
     *
     * @mbg.generated Mon Dec 21 23:41:42 CST 2020
     */
    long countByExample(BedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_bed
     *
     * @mbg.generated Mon Dec 21 23:41:42 CST 2020
     */
    int deleteByExample(BedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_bed
     *
     * @mbg.generated Mon Dec 21 23:41:42 CST 2020
     */
    int deleteByPrimaryKey(Integer bedId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_bed
     *
     * @mbg.generated Mon Dec 21 23:41:42 CST 2020
     */
    int insert(Bed record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_bed
     *
     * @mbg.generated Mon Dec 21 23:41:42 CST 2020
     */
    int insertSelective(Bed record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_bed
     *
     * @mbg.generated Mon Dec 21 23:41:42 CST 2020
     */
    List<Bed> selectByExample(BedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_bed
     *
     * @mbg.generated Mon Dec 21 23:41:42 CST 2020
     */
    Bed selectByPrimaryKey(Integer bedId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_bed
     *
     * @mbg.generated Mon Dec 21 23:41:42 CST 2020
     */
    int updateByExampleSelective(@Param("record") Bed record, @Param("example") BedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_bed
     *
     * @mbg.generated Mon Dec 21 23:41:42 CST 2020
     */
    int updateByExample(@Param("record") Bed record, @Param("example") BedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_bed
     *
     * @mbg.generated Mon Dec 21 23:41:42 CST 2020
     */
    int updateByPrimaryKeySelective(Bed record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_bed
     *
     * @mbg.generated Mon Dec 21 23:41:42 CST 2020
     */
    int updateByPrimaryKey(Bed record);
}