package com.LiteTravel.web.mapper;

import com.LiteTravel.web.Model.Company;
import com.LiteTravel.web.Model.CompanyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CompanyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_company
     *
     * @mbg.generated Mon Dec 21 17:35:48 CST 2020
     */
    long countByExample(CompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_company
     *
     * @mbg.generated Mon Dec 21 17:35:48 CST 2020
     */
    int deleteByExample(CompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_company
     *
     * @mbg.generated Mon Dec 21 17:35:48 CST 2020
     */
    int deleteByPrimaryKey(Integer companyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_company
     *
     * @mbg.generated Mon Dec 21 17:35:48 CST 2020
     */
    int insert(Company record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_company
     *
     * @mbg.generated Mon Dec 21 17:35:48 CST 2020
     */
    int insertSelective(Company record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_company
     *
     * @mbg.generated Mon Dec 21 17:35:48 CST 2020
     */
    List<Company> selectByExample(CompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_company
     *
     * @mbg.generated Mon Dec 21 17:35:48 CST 2020
     */
    Company selectByPrimaryKey(Integer companyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_company
     *
     * @mbg.generated Mon Dec 21 17:35:48 CST 2020
     */
    int updateByExampleSelective(@Param("record") Company record, @Param("example") CompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_company
     *
     * @mbg.generated Mon Dec 21 17:35:48 CST 2020
     */
    int updateByExample(@Param("record") Company record, @Param("example") CompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_company
     *
     * @mbg.generated Mon Dec 21 17:35:48 CST 2020
     */
    int updateByPrimaryKeySelective(Company record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_company
     *
     * @mbg.generated Mon Dec 21 17:35:48 CST 2020
     */
    int updateByPrimaryKey(Company record);
}