package com.LiteTravel.web.mapper;

import com.LiteTravel.web.Model.FlightCompany;
import com.LiteTravel.web.Model.FlightCompanyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FlightCompanyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_flight_company
     *
     * @mbg.generated Sun Dec 20 14:41:59 CST 2020
     */
    long countByExample(FlightCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_flight_company
     *
     * @mbg.generated Sun Dec 20 14:41:59 CST 2020
     */
    int deleteByExample(FlightCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_flight_company
     *
     * @mbg.generated Sun Dec 20 14:41:59 CST 2020
     */
    int deleteByPrimaryKey(Integer companyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_flight_company
     *
     * @mbg.generated Sun Dec 20 14:41:59 CST 2020
     */
    int insert(FlightCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_flight_company
     *
     * @mbg.generated Sun Dec 20 14:41:59 CST 2020
     */
    int insertSelective(FlightCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_flight_company
     *
     * @mbg.generated Sun Dec 20 14:41:59 CST 2020
     */
    List<FlightCompany> selectByExample(FlightCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_flight_company
     *
     * @mbg.generated Sun Dec 20 14:41:59 CST 2020
     */
    FlightCompany selectByPrimaryKey(Integer companyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_flight_company
     *
     * @mbg.generated Sun Dec 20 14:41:59 CST 2020
     */
    int updateByExampleSelective(@Param("record") FlightCompany record, @Param("example") FlightCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_flight_company
     *
     * @mbg.generated Sun Dec 20 14:41:59 CST 2020
     */
    int updateByExample(@Param("record") FlightCompany record, @Param("example") FlightCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_flight_company
     *
     * @mbg.generated Sun Dec 20 14:41:59 CST 2020
     */
    int updateByPrimaryKeySelective(FlightCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_flight_company
     *
     * @mbg.generated Sun Dec 20 14:41:59 CST 2020
     */
    int updateByPrimaryKey(FlightCompany record);
}