package com.LiteTravel.web.mapper;

import com.LiteTravel.web.Model.Hotel;
import com.LiteTravel.web.Model.HotelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HotelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_hotel
     *
<<<<<<< Updated upstream
     * @mbg.generated Thu Dec 10 23:46:40 CST 2020
=======
     * @mbg.generated Sun Dec 20 22:43:15 CST 2020
>>>>>>> Stashed changes
     */
    long countByExample(HotelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_hotel
     *
<<<<<<< Updated upstream
     * @mbg.generated Thu Dec 10 23:46:40 CST 2020
=======
     * @mbg.generated Sun Dec 20 22:43:15 CST 2020
>>>>>>> Stashed changes
     */
    int deleteByExample(HotelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_hotel
     *
<<<<<<< Updated upstream
     * @mbg.generated Thu Dec 10 23:46:40 CST 2020
=======
     * @mbg.generated Sun Dec 20 22:43:15 CST 2020
>>>>>>> Stashed changes
     */
    int deleteByPrimaryKey(Integer hotelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_hotel
     *
<<<<<<< Updated upstream
     * @mbg.generated Thu Dec 10 23:46:40 CST 2020
=======
     * @mbg.generated Sun Dec 20 22:43:15 CST 2020
>>>>>>> Stashed changes
     */
    int insert(Hotel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_hotel
     *
<<<<<<< Updated upstream
     * @mbg.generated Thu Dec 10 23:46:40 CST 2020
=======
     * @mbg.generated Sun Dec 20 22:43:15 CST 2020
>>>>>>> Stashed changes
     */
    int insertSelective(Hotel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_hotel
     *
<<<<<<< Updated upstream
     * @mbg.generated Thu Dec 10 23:46:40 CST 2020
     */
    List<Hotel> selectByExampleWithBLOBs(HotelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_hotel
     *
     * @mbg.generated Thu Dec 10 23:46:40 CST 2020
=======
     * @mbg.generated Sun Dec 20 22:43:15 CST 2020
>>>>>>> Stashed changes
     */
    List<Hotel> selectByExample(HotelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_hotel
     *
<<<<<<< Updated upstream
     * @mbg.generated Thu Dec 10 23:46:40 CST 2020
=======
     * @mbg.generated Sun Dec 20 22:43:15 CST 2020
>>>>>>> Stashed changes
     */
    Hotel selectByPrimaryKey(Integer hotelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_hotel
     *
<<<<<<< Updated upstream
     * @mbg.generated Thu Dec 10 23:46:40 CST 2020
=======
     * @mbg.generated Sun Dec 20 22:43:15 CST 2020
>>>>>>> Stashed changes
     */
    int updateByExampleSelective(@Param("record") Hotel record, @Param("example") HotelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_hotel
     *
<<<<<<< Updated upstream
     * @mbg.generated Thu Dec 10 23:46:40 CST 2020
     */
    int updateByExampleWithBLOBs(@Param("record") Hotel record, @Param("example") HotelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_hotel
     *
     * @mbg.generated Thu Dec 10 23:46:40 CST 2020
=======
     * @mbg.generated Sun Dec 20 22:43:15 CST 2020
>>>>>>> Stashed changes
     */
    int updateByExample(@Param("record") Hotel record, @Param("example") HotelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_hotel
     *
<<<<<<< Updated upstream
     * @mbg.generated Thu Dec 10 23:46:40 CST 2020
=======
     * @mbg.generated Sun Dec 20 22:43:15 CST 2020
>>>>>>> Stashed changes
     */
    int updateByPrimaryKeySelective(Hotel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_hotel
     *
<<<<<<< Updated upstream
     * @mbg.generated Thu Dec 10 23:46:40 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(Hotel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_hotel
     *
     * @mbg.generated Thu Dec 10 23:46:40 CST 2020
=======
     * @mbg.generated Sun Dec 20 22:43:15 CST 2020
>>>>>>> Stashed changes
     */
    int updateByPrimaryKey(Hotel record);
}