package com.LiteTravel.web.mapper;

import com.LiteTravel.web.Model.RoomBedMap;
import com.LiteTravel.web.Model.RoomBedMapExample;
import com.LiteTravel.web.Model.RoomBedMapKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RoomBedMapMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_room_bed
     *
<<<<<<< Updated upstream
     * @mbg.generated Thu Dec 10 23:46:40 CST 2020
=======
     * @mbg.generated Sun Dec 20 22:43:15 CST 2020
>>>>>>> Stashed changes
     */
    long countByExample(RoomBedMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_room_bed
     *
<<<<<<< Updated upstream
     * @mbg.generated Thu Dec 10 23:46:40 CST 2020
=======
     * @mbg.generated Sun Dec 20 22:43:15 CST 2020
>>>>>>> Stashed changes
     */
    int deleteByExample(RoomBedMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_room_bed
     *
<<<<<<< Updated upstream
     * @mbg.generated Thu Dec 10 23:46:40 CST 2020
=======
     * @mbg.generated Sun Dec 20 22:43:15 CST 2020
>>>>>>> Stashed changes
     */
    int deleteByPrimaryKey(RoomBedMapKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_room_bed
     *
<<<<<<< Updated upstream
     * @mbg.generated Thu Dec 10 23:46:40 CST 2020
=======
     * @mbg.generated Sun Dec 20 22:43:15 CST 2020
>>>>>>> Stashed changes
     */
    int insert(RoomBedMap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_room_bed
     *
<<<<<<< Updated upstream
     * @mbg.generated Thu Dec 10 23:46:40 CST 2020
=======
     * @mbg.generated Sun Dec 20 22:43:15 CST 2020
>>>>>>> Stashed changes
     */
    int insertSelective(RoomBedMap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_room_bed
     *
<<<<<<< Updated upstream
     * @mbg.generated Thu Dec 10 23:46:40 CST 2020
=======
     * @mbg.generated Sun Dec 20 22:43:15 CST 2020
>>>>>>> Stashed changes
     */
    List<RoomBedMap> selectByExample(RoomBedMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_room_bed
     *
<<<<<<< Updated upstream
     * @mbg.generated Thu Dec 10 23:46:40 CST 2020
=======
     * @mbg.generated Sun Dec 20 22:43:15 CST 2020
>>>>>>> Stashed changes
     */
    RoomBedMap selectByPrimaryKey(RoomBedMapKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_room_bed
     *
<<<<<<< Updated upstream
     * @mbg.generated Thu Dec 10 23:46:40 CST 2020
=======
     * @mbg.generated Sun Dec 20 22:43:15 CST 2020
>>>>>>> Stashed changes
     */
    int updateByExampleSelective(@Param("record") RoomBedMap record, @Param("example") RoomBedMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_room_bed
     *
<<<<<<< Updated upstream
     * @mbg.generated Thu Dec 10 23:46:40 CST 2020
=======
     * @mbg.generated Sun Dec 20 22:43:15 CST 2020
>>>>>>> Stashed changes
     */
    int updateByExample(@Param("record") RoomBedMap record, @Param("example") RoomBedMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_room_bed
     *
<<<<<<< Updated upstream
     * @mbg.generated Thu Dec 10 23:46:40 CST 2020
=======
     * @mbg.generated Sun Dec 20 22:43:15 CST 2020
>>>>>>> Stashed changes
     */
    int updateByPrimaryKeySelective(RoomBedMap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_room_bed
     *
<<<<<<< Updated upstream
     * @mbg.generated Thu Dec 10 23:46:40 CST 2020
=======
     * @mbg.generated Sun Dec 20 22:43:15 CST 2020
>>>>>>> Stashed changes
     */
    int updateByPrimaryKey(RoomBedMap record);
}