package com.LiteTravel.web.mapper;

import com.LiteTravel.web.Model.Room;
import com.LiteTravel.web.Model.RoomExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RoomMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_hotel_room
     *
<<<<<<< Updated upstream
     * @mbg.generated Thu Dec 10 23:46:40 CST 2020
=======
     * @mbg.generated Sun Dec 20 22:43:15 CST 2020
>>>>>>> Stashed changes
     */
    long countByExample(RoomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_hotel_room
     *
<<<<<<< Updated upstream
     * @mbg.generated Thu Dec 10 23:46:40 CST 2020
=======
     * @mbg.generated Sun Dec 20 22:43:15 CST 2020
>>>>>>> Stashed changes
     */
    int deleteByExample(RoomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_hotel_room
     *
<<<<<<< Updated upstream
     * @mbg.generated Thu Dec 10 23:46:40 CST 2020
=======
     * @mbg.generated Sun Dec 20 22:43:15 CST 2020
>>>>>>> Stashed changes
     */
    int deleteByPrimaryKey(Integer roomId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_hotel_room
     *
<<<<<<< Updated upstream
     * @mbg.generated Thu Dec 10 23:46:40 CST 2020
=======
     * @mbg.generated Sun Dec 20 22:43:15 CST 2020
>>>>>>> Stashed changes
     */
    int insert(Room record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_hotel_room
     *
<<<<<<< Updated upstream
     * @mbg.generated Thu Dec 10 23:46:40 CST 2020
=======
     * @mbg.generated Sun Dec 20 22:43:15 CST 2020
>>>>>>> Stashed changes
     */
    int insertSelective(Room record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_hotel_room
     *
<<<<<<< Updated upstream
     * @mbg.generated Thu Dec 10 23:46:40 CST 2020
=======
     * @mbg.generated Sun Dec 20 22:43:15 CST 2020
>>>>>>> Stashed changes
     */
    List<Room> selectByExampleWithBLOBs(RoomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_hotel_room
     *
<<<<<<< Updated upstream
     * @mbg.generated Thu Dec 10 23:46:40 CST 2020
=======
     * @mbg.generated Sun Dec 20 22:43:15 CST 2020
>>>>>>> Stashed changes
     */
    List<Room> selectByExample(RoomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_hotel_room
     *
<<<<<<< Updated upstream
     * @mbg.generated Thu Dec 10 23:46:40 CST 2020
=======
     * @mbg.generated Sun Dec 20 22:43:15 CST 2020
>>>>>>> Stashed changes
     */
    Room selectByPrimaryKey(Integer roomId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_hotel_room
     *
<<<<<<< Updated upstream
     * @mbg.generated Thu Dec 10 23:46:40 CST 2020
=======
     * @mbg.generated Sun Dec 20 22:43:15 CST 2020
>>>>>>> Stashed changes
     */
    int updateByExampleSelective(@Param("record") Room record, @Param("example") RoomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_hotel_room
     *
<<<<<<< Updated upstream
     * @mbg.generated Thu Dec 10 23:46:40 CST 2020
=======
     * @mbg.generated Sun Dec 20 22:43:15 CST 2020
>>>>>>> Stashed changes
     */
    int updateByExampleWithBLOBs(@Param("record") Room record, @Param("example") RoomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_hotel_room
     *
<<<<<<< Updated upstream
     * @mbg.generated Thu Dec 10 23:46:40 CST 2020
=======
     * @mbg.generated Sun Dec 20 22:43:15 CST 2020
>>>>>>> Stashed changes
     */
    int updateByExample(@Param("record") Room record, @Param("example") RoomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_hotel_room
     *
<<<<<<< Updated upstream
     * @mbg.generated Thu Dec 10 23:46:40 CST 2020
=======
     * @mbg.generated Sun Dec 20 22:43:15 CST 2020
>>>>>>> Stashed changes
     */
    int updateByPrimaryKeySelective(Room record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_hotel_room
     *
<<<<<<< Updated upstream
     * @mbg.generated Thu Dec 10 23:46:40 CST 2020
=======
     * @mbg.generated Sun Dec 20 22:43:15 CST 2020
>>>>>>> Stashed changes
     */
    int updateByPrimaryKeyWithBLOBs(Room record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_hotel_room
     *
<<<<<<< Updated upstream
     * @mbg.generated Thu Dec 10 23:46:40 CST 2020
=======
     * @mbg.generated Sun Dec 20 22:43:15 CST 2020
>>>>>>> Stashed changes
     */
    int updateByPrimaryKey(Room record);
}